### DISCUSSION TITLE
Custom ressources

### DISCUSSION THREAD

**Discussion by Fenrur** [emqx/emqx-operator#1010] [Ideas]
# First idea

Hello, I will see a feature that will help **GitOps** a lot.

A **user custom resource**, where we indicate in this custom resource, the name of the Emqx resource, the name of the user.

The operator would carry out the creation and reconciliation operations if in the db, the user is deleted manually to avoid any problems.

Once the resource is applied, a secret is created in the same namespace as the `User` resource.

secret name:
`same user ressource name`

This is composed of:
- `user` = `user` + `-` + `random uuid`
- `password` = a random strong password
- `emqx` = the associated emqx

**Example**

**user-emqx.yml:**

```yml
apiVersion: apps.emqx.io/.......
kind: User
metadata:
  namespace: hello
  name:  fenrur-user-emqx
spec:
  generateUserName: fenrur
  emqx: my-emqx
```

**secret name created by the operator:**

```yml
apiVersion: v1
kind: Secret
metadata:
  namespace: hello
  name:  fenrur-user-emqx
  labels:
    apps.emqx.io/managed-by: "emqx-operator"
    apps.emqx.io/instance: "my-emqx"
    ...
data:
   user: fenrur-447483bc-30d1-42a3-bab8-898abfae9afc
   password: STRONG PASSWORD
   emqx: my-emqx
type: Opaque
```

# Second idea

But the best would be to have all the UI behavior as a custom resource.
<img width="153" alt="Capture d’écran 2024-02-08 à 12 53 53" src="https://github.com/emqx/emqx-operator/assets/26191768/1bdd6684-1852-41d8-b2ba-b50a12153d52">
<img width="153" alt="Capture d’écran 2024-02-08 à 12 54 09" src="https://github.com/emqx/emqx-operator/assets/26191768/2a4a861e-7389-45d9-836b-30bbe9926d21">
