### DISCUSSION TITLE
How to tail emqx container's stdout in telegraf sidecar container.

### DISCUSSION THREAD

**Discussion by ghost** [emqx/emqx-operator#328] [Q&A] [answered]
If I need to read the emqx log use telegraf sidecar
What can I do now, because the emqx log is oriented to stdout.

the one way is to mount emqx container stdout file by hostPath, but the implementation is too complex。

is there any other sample way to achieve the target。

**Comment by Rory-Z** [comment, marked as answer]
Maybe you can printout EMQX log to emptyDir ，just like this:

```
apiVersion: apps.emqx.io/v1beta3
kind: EmqxBroker
metadata:
  name: emqx
spec:
  emqxTemplate:
    image: emqx/emqx:4.4.6
    config:
      log.to: both
      log.dir: /mounted/log
    extraVolumeMounts:
    - name: logs
      mountPath: /mounted/log 
    extraVolumes:
    - name: logs
      emptyDir: {}
```
