### DISCUSSION TITLE
How to set timezone for the EMQX container?

### DISCUSSION THREAD

**Discussion by jacky-xbb** [emqx/emqx-operator#338] [Q&A] [answered]
Hi, guys

I want to change the timezone of the EMQX container. Is there a convenient way to implement it?

**Comment by jacky-xbb** [comment, marked as answer]
1. Create a ConfigMap to import the time zone settings that you want to use.
  For other time zones, use the corresponding files in the `/usr/share/zoneinfo/Asia/` directory. Example:

    ```
    kubectl create configmap tz --from-file=/usr/share/zoneinfo/Asia/Shanghai
    ```

2. Mount the ConfigMap in a emqx yaml.

    ```
    cat << "EOF" | kubectl apply -f -
    apiVersion: apps.emqx.io/v1beta3
    kind: EmqxEnterprise
    metadata:
      name: emqx-ee
      labels:
        "foo": "bar"
    spec:
      emqxTemplate:
        image: emqx/emqx-ee:4.4.6
        extraVolumeMounts:
        - name: tz
          mountPath: /etc/localtime
          subPath: Shanghai
        extraVolumes:
        - name: tz
          configMap:
            name: tz
    EOF
    ```

3. Check if the time zone validated

    ```
    kubectl exec -it emqx-ee-0 -c emqx -- bash -c "date -R"
    ```

    You will find the time zone being changed Shanghai.
