### DISCUSSION TITLE
How to update EMQX resource when using bootstrapConfig

### DISCUSSION THREAD

**Discussion by mariusstaicu** [emqx/emqx-operator#471] [Q&A] [answered]
When using bootstrapConfig one cannot reapply the yaml and update other portions of it because of the validation error:
```
admission webhook "validator.apps.emqx.io" denied the request: bootstrap config cannot be updated, old bootstrap config: 
```

How to update the EQMX resource without this validation failure?

**Comment by Rory-Z** [comment]
Please update EMQX Operator to 2.0.1 and try again, I think I fixed it in 2.0.1, if this problem still exists, please let me know

**Reply by mariusstaicu** [reply]
I'm using 2.0.1 already and this still happens.

**Reply by Rory-Z** [reply]
Could you please share the YAML file for deploying EMQX?

**Reply by mariusstaicu** [reply]
```yaml
apiVersion: apps.emqx.io/v2alpha1
kind: EMQX
metadata:
  name: emqx
  namespace: infrastructure
spec:
  image: emqx/emqx:5.0.10
  bootstrapConfig: |
    listeners.tcp.default {
      bind = "0.0.0.0:1883"
      max_connections = 1024000
    }
    listeners.ssl.mqtts {
      bind = "0.0.0.0:8883"
    
      max_connections = 102400
    
      ssl_options {
        keyfile = "/etc/certs/tls.key"
        certfile = "/etc/certs/tls.crt"
        versions = ["tlsv1.3", "tlsv1.2", "tlsv1.1", "tlsv1"]
      }
    }
  coreTemplate:
    metadata:
      name: emqx-core
      labels:
        apps.emqx.io/instance: emqx
        apps.emqx.io/db-role: core
    spec:
      initContainers:
        - name: sysctl-buddy
          image: busybox:1.31
          securityContext:
            privileged: true
          command: [ "/bin/sh" ]
          args:
            - -c
            - sysctl -w fs.file-max=2097152 fs.nr_open=2097152 net.core.somaxconn=32768 net.ipv4.tcp_max_syn_backlog=16384 net.netfilter.nf_conntrack_max=1000000 net.netfilter.nf_conntrack_tcp_timeout_time_wait=30 net.ipv4.tcp_max_tw_buckets=1048576 net.ipv4.tcp_fin_timeout=15
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 10m
              memory: 10Mi
      extraContainers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.30.1
          command: [ "/cloud_sql_proxy",
                     "-instances=compelling-cat-212513:europe-west2:integration=tcp:5432",
                     "-credential_file=/secrets/cloudsql/cloud-sql-service-account.json" ]
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: cloud-sql-service-account
              mountPath: /secrets/cloudsql
              readOnly: true
      replicas: 3
      volumeClaimTemplates:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
      livenessProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 60
        periodSeconds: 30
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 12
      podSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
      extraVolumeMounts:
        - name: emqx-certs
          mountPath: /etc/certs
          readOnly: true
        - name: cloud-sql-service-account
          mountPath: /secrets/cloudsql
          readOnly: true
      extraVolumes:
        - name: emqx-certs
          secret:
            secretName: emqx-certificate
        - name: cloud-sql-service-account
          secret:
            secretName: cloud-sql-service-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: apps.emqx.io/instance
                      operator: In
                      values:
                        - emqx
                topologyKey: "kubernetes.io/hostname"
              weight: 1
```
