### DISCUSSION TITLE
How do modify EMQX 5.0‘s acl.conf in EMQX Operator

### DISCUSSION THREAD

**Discussion by 18434831316** [emqx/emqx-operator#689] [Q&A] [answered]
how do modify emqx-operator  acla.conf

**Comment by Rory-Z** [comment]
Could you tell me the EMQX version and EMQX Operator version ?

**Reply by 18434831316** [reply]
EMQX5   EMQX Operator2.1.1

**Comment by Rory-Z** [comment, marked as answer]
Hi @18434831316 you can create configMap by your self, and use `.spec.[coreTemplate | replicantTemplate].extraVolumes` and `.spec.[coreTemplate | replicantTemplate].extraVolumeMounts` to mounted it. like this
```
apiVersion: apps.emqx.io/v2alpha1
kind: EMQX
metadata:
  name: emqx
spec:
  image: emqx:5.0
  coreTemplate:
    spec:
      extraVolumes:
      - name: my-owner-acl
        configMap:  fake-acl-conf
      extraVolumeMounts:
      - name: my-owner-acl
        mountPath: /opt/emqx/etc/acl.conf
        subPath: acl.conf
  replicantTemplate:
    spec:
      extraVolumes:
      - name: my-owner-acl
        configMap:  fake-acl-conf
      extraVolumeMounts:
      - name: my-owner-acl
        mountPath: /opt/emqx/etc/acl.conf
        subPath: acl.conf
```
