### DISCUSSION TITLE
emqx5 obtains the real IP address , how to config emqx-operator2.1.1

### DISCUSSION THREAD

**Discussion by 18434831316** [emqx/emqx-operator#698] [Q&A]
![Uploading 1680596815975.jpg…]()

**Comment by 18434831316** [comment]
![1680596815975](https://user-images.githubusercontent.com/48436969/229735600-cabd2d37-8d3b-4653-8d74-147ec44409b0.jpg)

**Comment by Rory-Z** [comment]
Well, need configure `proxy_protocol` in EMQX listener and LoadBalance, you can via EMQX Dashboard to enable it in EMQX, for LoadBalance, need resources for your service provider

**Reply by 18434831316** [reply]
```yaml
apiVersion: apps.emqx.io/v2alpha1
kind: EMQX
metadata:
  name: emqx
spec:
  image: emqx:5.0
  bootstrapConfig: |
    log {
      file_handlers.default {
        level: warning
        file: "log/emqx.log"
      }
    }

    listeners.tcp.default {
      bind: "0.0.0.0:1883"
      max_connections: 1024000
      proxy_protocol: true
    }

    listeners.ssl.default {
      bind: "0.0.0.0:8883"
      max_connections: 512000
      proxy_protocol: true
      ssl_options {
        keyfile: "etc/certs/key.pem"
        certfile: "etc/certs/cert.pem"
        cacertfile: "etc/certs/cacert.pem"
      }
    }

    listeners.ws.default {
      bind: "0.0.0.0:8083"
      max_connections: 1024000
      websocket.mqtt_path: "/mqtt"
      proxy_protocol: true
    }

    listeners.wss.default {
      bind: "0.0.0.0:8084"
      max_connections: 512000
      proxy_protocol: true
      websocket.mqtt_path: "/mqtt"
      ssl_options {
        keyfile: "etc/certs/key.pem"
        certfile: "etc/certs/cert.pem"
        cacertfile: "etc/certs/cacert.pem"
      }
    }

    dashboard {
        listeners.http {
            bind: 18083
        }
    }

    authorization {
      deny_action: ignore
      no_match: allow
      sources: [
        {
          type: file
          path: "etc/acl.conf"
        }
      ]
    }

  coreTemplate:
    spec:
      volumeClaimTemplates:
        storageClassName: nfs-client
        resources:
          requests:
            storage: 10Gi
        accessModes:
        - ReadWriteOnce
      replicas: 2
      extraVolumeMounts:
      - name: acl-conf
        mountPath: /opt/emqx/etc/acl.conf
        subPath: acl.conf
      extraVolumes:
      - name: acl-conf
        configMap: 
          name: acl-cm

  replicantTemplate:
    spec:
      replicas: 3
      extraVolumeMounts:
      - name: acl-conf
        mountPath: /opt/emqx/etc/acl.conf
        subPath: acl.conf
      extraVolumes:
      - name: acl-conf
        configMap: 
          name: acl-cm
  
  dashboardServiceTemplate:
    spec:
      type: NodePort
      ports:
      - name: "dashboard-listeners-http-bind"
        protocol: TCP
        port: 18083
        targetPort: 18083
        nodePort: 32009


```

is right?
