### DISCUSSION TITLE
Create `/opt/emqx/data/config` failed, looks permission denied

### DISCUSSION THREAD

**Discussion by Rory-Z** [emqx/emqx-operator#716] [Q&A] [answered]
When I deploy EMQX cluster on public cloud platforms, and I want use `storeClass` to persistence EMQX cluster data, and I will get this error in EMQX pod:

```
$ kubectl logs emqx-ee-0 -c emqx

2023-04-14T04:08:50.571832+00:00 [error] Error creating /opt/emqx/data/configs; permission denied
```

How to resolve it ?

**Comment by Rory-Z** [comment, marked as answer]
Please add `PodSecurityContext` in EMQX custom resource like this:

+ in `apps.emqx.io/v1beta4`
```
apiVersion: apps.emqx.io/v1beta4
kind: EmqxEnterprise
metadata:
  name: emqx-ee
spec:
  persistent:
    metadata:
      name: emqx-ee
    spec:
      storageClassName: gce-pd
      resources:
        requests:
          storage: 20Mi
      accessModes:
        - ReadWriteOnce
  template:
    spec:
      podSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always
        supplementalGroups:
          - 1000
      emqxContainer:
        image:
          repository: emqx/emqx-ee
          version: 4.4.15
```

+ in `apps.emqx.io/v2alpha1`
```
apiVersion: apps.emqx.io/v2alpha1
kind: EMQX
metadata:
  name: emqx
spec:
  image: "emqx:5.0"
  coreTemplate:
    spec:
      podSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always
        supplementalGroups:
          - 1000
      volumeClaimTemplates:
        storageClassName: gce-pd
        resources:
          requests:
            storage: 20Mi
        accessModes:
        - ReadWriteOnce
```
