### DISCUSSION TITLE
How can I modify emqx.conf

### DISCUSSION THREAD

**Discussion by ASCE1885** [emqx/emqx-operator#770] [Q&A]
I deploy the emqx cluster through emqx-operator, and I want to modify zone.external.max_mqueue_len in emqx.conf file, but I can not find the entry of this file. My deploy command is as below, the emqx verison is 4.4.15
```yaml
cat << "EOF" | kubectl apply -f -
apiVersion: apps.emqx.io/v1beta4
kind: EmqxBroker
metadata:
   name: emqx
   namespace: fedml-infra-emqx
spec:
   template:
     spec:
       emqxContainer:
         image:
           repository: emqx
           version: "4.4.15"
EOF
```

**Comment by Rory-Z** [comment]
Hi, @ASCE1885 You can modify emqx.conf like this:
```
cat << "EOF" | kubectl apply -f -
apiVersion: apps.emqx.io/v1beta4
kind: EmqxBroker
metadata:
   name: emqx
   namespace: fedml-infra-emqx
spec:
   template:
     spec:
       emqxContainer:
         image:
           repository: emqx
           version: "4.4.15"
         emqxConfig:
           zone.external.max_mqueue_len: ${you_want_value}
EOF
```
