### DISCUSSION TITLE
Questions about EMQX operator 2.2.0

### DISCUSSION THREAD

**Discussion by DjSnakekk** [emqx/emqx-operator#913] [Q&A]
version:
emqx-operator-controller:2.2.0

1: The memory displayed on the dashboard I deployed is from the host machine.
2: The nodeport port number of the service built by the operator will keep refreshing. 
How should I configure it?

my yaml
```
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: emqx:5.1
  listenersServiceTemplate:
    spec:
      type: LoadBalancer
  dashboardServiceTemplate:
    spec:
      type: LoadBalancer
  coreTemplate:
    spec:
      replicas: 3
      resources:
        limits:
          cpu: '4'
          memory: 10Gi
        requests:
          cpu: 4
          memory: 8Gi
  replicantTemplate:
    spec:
      replicas: 3
      resources:
        limits:
          cpu: '4'
          memory: 10Gi
        requests:
          cpu: 4
          memory: 8Gi
```
