### DISCUSSION TITLE
Generate an api key (programatically)

### DISCUSSION THREAD

**Discussion by klemen-df** [emqx/emqx-operator#953] [Q&A] [answered]
I would like to programatically generate an api key - any advice how to do this with this operator?

**Comment by Rory-Z** [comment]
If you didn't set any api key, the EMQX Operator will generate a default api key, you can get it after deploy EMQX customer resource, like  `kubectl get secret`

**Comment by klemen-df** [comment]
Hi,

I would like to set an additional one (multiple).

Kind regards, Klemen

Poslano iz Outlook za Android<https://aka.ms/AAb9ysg>


Classified as Business

________________________________

**Comment by Rory-Z** [comment]
Hi @KlemenDanfoss you can add you owner api key in EMQX customer resource by `.spec.bootstrapAPIKeys`

**Comment by klemen-df** [comment]
Hi @Rory-Z , I would like to set additional keys (also) after deployment.

For now it says that 'bootstrap APIKey cannot be updated'

Using operator 2.1.2 and emqx 5.0.24.

**Reply by Rory-Z** [reply]
Sorry for delay, I just finished my vacation.
For now, you can not change APIKeys after deployment, because the EMQX did not support it, but you can change APIKeys via EMQX dashboard.
Maybe we will supporting this feature in future versions.

**Reply by klemen-df** [reply]
ty

**Comment by badsector3** [comment]
Instead of creating new topic, I just add here. I try to add my own bootstrapAPIKey, but the values have to be read from k8s secret. 
I was able to make it work using `helm update --install` but cannot make it to work with ArgoCD. 
 
I use the following CRD:
```
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: {{ include "emqx-operator-crd.fullname" . }}
  labels:
     {{- include "emqx-operator-crd.labels" . | nindent 4 }}
spec:
   {{- $secretData := (lookup "v1" "Secret" "mqtt" "emqx-operator-crd-bootstrap").data }}
  bootstrapAPIKeys:
    - key: {{ $secretData.NAME | b64dec | quote }}
      secret: {{ $secretData.SECRET | b64dec | quote }}  
````

The bootstrapAPIKeys works fine if I just provide plane key/secret, but from obvious reasons I cannot commit such creds to Github. 
I tried to replace the secret generated by the operator `emqx-operator-crd-bootstrap-api-key` but it doesn't work. Complaining about missing `bootstrap_api_key` which exists. 
I tried to mount external volume and replace the destination path, but it doesn't work either

Any ideas how to solve it? I need to add own bootstrapAPIKey which is used by other microservice

**Reply by badsector3** [reply]
Yeah, just confirmed where the problem is if I change the `EMQX_API_KEY__BOOTSTRAP_FILE`

```
failed to get node statues by API: failed to get API http://10.x.x.x:18083/api/v5/nodes, status : 401 Unauthorized, body: {"code":"BAD_API_KEY_OR_SECRET","message":"Check api_key/api_secret"}
```

so the CRD looks now:
```
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: {{ include "emqx-operator-crd.fullname" . }}
  labels:
     {{- include "emqx-operator-crd.labels" . | nindent 4 }}
spec:
  coreTemplate:
    spec: 
      extraVolumes:
      - name: emqx-license
        secret:
          secretName: {{ .Values.emqxLicenseSecretName }}   
      - name: emqx-bootstrap-api-key
        secret:
          secretName: {{ .Values.emqxBootstrapAPIKey }}                   
      extraVolumeMounts:
      - name: emqx-license
        mountPath: "/opt/emqx/etc/emqx.lic"
        subPath: "emqx.lic"
        readOnly: true                  
      - name: emqx-bootstrap-api-key
        mountPath: "/opt/emqx/data/custom_bootstrap_api_key"
        subPath: "bootstrap_api_key"
        readOnly: true             
      env:
        - name: EMQX_API_KEY__BOOTSTRAP_FILE
          value: "/opt/emqx/data/custom_bootstrap_api_key" 
```

**Reply by badsector3** [reply]
Replacing the bootstrapAPIKey by creating custom secret  `emqx-operator-crd-bootstrap-api-key` error:

```
{"level":"error","ts":"2023-10-11T19:05:39Z","msg":"Reconciler error","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","eMQX":{"name":"emqx-operator-crd","namespace":"mqtt"},"namespace":"mqtt","name":"emqx-operator-crd","reconcileID":"d889f271-9611-4793-9dfe-a3cb56054b52","error":"failed to get bootstrap user: the secret does not contain the bootstrap_api_key","errorVerbose":"the secret does not contain the bootstrap_api_key\ngithub.com/emqx/emqx-operator/controllers/apps/v2beta1.getBootstrapAPIKey\n\t/workspace/controllers/apps/v2beta1/emqx_controller.go:237\ngithub.com/emqx/emqx-operator/controllers/apps/v2beta1.newRequester\n\t/workspace/controllers/apps/v2beta1/emqx_controller.go:158\ngithub.com/emqx/emqx-operator/controllers/apps/v2beta1.(*EMQXReconciler).Reconcile\n\t/workspace/controllers/apps/v2beta1/emqx_controller.go:104\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\nfailed to get bootstrap user\ngithub.com/emqx/emqx-operator/controllers/apps/v2beta1.(*EMQXReconciler).Reconcile\n\t/workspace/controllers/apps/v2beta1/emqx_controller.go:110\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
```

BTW the new secret looks fine to me:
```
apiVersion: v1
data:
  bootstrap_api_key: xxxxxxx
immutable: false
kind: Secret
```

**Reply by Rory-Z** [reply]
Hi @badsector3 nice try, but this may cause some features of EMQX Operator to be not work.

**Comment by Rory-Z** [comment]
Hi @badsector3 @KlemenDanfoss the bootstrapAPIKeys will support secret in coming soon, any ideas for the following CRD example :
```
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: emqx:5.1
  bootstrapAPIKeys:
  - key: foo
    secret: bar
  ## support secret
  - secretRef:
      key:
        secretName: some-secret
        secretKey: some-key
      secret:
        secretName: some-secret
        secretKey: some-key
```
Please note that secret resources are only valid when emqx is started. Once emqx is completed, they become meaningless, whether modified or deleted.

**Reply by klemen-df** [reply]
@Rory-Z So this is more like bootstrap config - only can be set once at the time of the installation and then never changed?

**Reply by badsector3** [reply]
Hi @Rory-Z. Your's approach doesn't work. Getting:
```
W1012 10:47:45.098686   76146 warnings.go:70] unknown field "spec.bootstrapAPIKeys[1].secretRef"
Error: 1 error occurred:
	* EMQX.apps.emqx.io "emqx-operator-crd" is invalid: [spec.bootstrapAPIKeys[1].key: Required value, spec.bootstrapAPIKeys[1].secret: Required value]
```

Looking at CRD schema we have:
```
    name: v2beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              bootstrapAPIKeys:
                items:
                  properties:
                    key:
                      pattern: ^[a-zA-Z\d-_]+$
                      type: string
                    secret:
                      maxLength: 32
                      minLength: 3
                      type: string
                  required:
                  - key
                  - secret
                  type: object
                type: array
```

**Reply by badsector3** [reply]
@Rory-Z - sorry, did you mean that the provided code by you was a proposal, right? 
If so - that looks fine - as long as we can pass values from k8s secret - that's all I need.

BTW - what about the licence? The same issue as with bootstrapAPIKey - almost. 
There is no key for licence in CRD, so the only way to push the licence is to add it to the config key, where again we cannot use k8s secrets.
Its just reminder - bootstrapAPIKey is more critical IMO.

**Reply by Rory-Z** [reply]
> @Rory-Z So this is more like bootstrap config - only can be set once at the time of the installation and then never changed?

@KlemenDanfoss Yes, the EMQX didn't print API secret after create API key in anyway,  so the bootstrap API keys just set once

**Reply by Rory-Z** [reply]
> If so - that looks fine - as long as we can pass values from k8s secret - that's all I need.

@badsector3  Great ! Thank you ! Please follow our new version

> BTW - what about the licence?

A hack way: create a secret of license, and use it in Pod env by valueFrom, like following:
```
apiVersion: v1
kind: Secret
metadata:
  name: emqx-license
data:
  license: <base64 encoded license>
---
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: emqx:5.1
  coreTemplate:
    spec:
      env:
      - name: EMQX__LICENSE__KEY
        valueFrom:
          secretKeyRef:
            name: emqx-license
            key: license
```
