### DISCUSSION TITLE
The replicat node cannot start after configuring PVC

### DISCUSSION THREAD

**Discussion by DjSnakekk** [emqx/emqx-operator#955] [Q&A]
version:
emqx-operator-controller:2.2.0

when i config PVC
core node start  replicat node cannot start
i can't find any error log from  core node and opreator

yaml:
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx1
spec:
  image: emqx:5.1
  listenersServiceTemplate:
    spec:
      type: LoadBalancer
  dashboardServiceTemplate:
    spec:
      type: LoadBalancer
  coreTemplate:
    spec:
      volumeClaimTemplates:
        storageClassName: cloud-hp1-delete
        resources:
          requests:
            storage: 10Gi
        accessModes:
          - ReadWriteOnce
      replicas: 3
      resources:
        limits:
          cpu: '4'
          memory: 10Gi
        requests:
          cpu: 4
          memory: 8Gi
  replicantTemplate:
    spec:
      replicas: 3
      resources:
        limits:
          cpu: '4'
          memory: 10Gi
        requests:
          cpu: 4
          memory: 8Gi

**Comment by Rory-Z** [comment]
Hi, @DjSnakekk the replicant node is stateless node, so they didn't need PVC.

**Reply by DjSnakekk** [reply]
My replicat node is not configured with PVC
```
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx1
spec:
  image: emqx:5.1
  listenersServiceTemplate:
    spec:
      type: LoadBalancer
  dashboardServiceTemplate:
    spec:
      type: LoadBalancer
  coreTemplate:
    spec:
      volumeClaimTemplates:
        storageClassName: cloud-hp1-delete
        resources:
          requests:
            storage: 10Gi
        accessModes:
          - ReadWriteOnce
      replicas: 3
      resources:
        limits:
          cpu: '4'
          memory: 6Gi
        requests:
          cpu: 4
          memory: 4Gi
  replicantTemplate:
    spec:
      replicas: 3
      resources:
        limits:
          cpu: '4'
          memory: 6Gi
        requests:
          cpu: 4
          memory: 4Gi
```
