### DISCUSSION TITLE
Env variables for schema_registry

### DISCUSSION THREAD

**Discussion by badsector3** [emqx/emqx-operator#964] [Q&A] [answered]
Hi.

   I have a question about env variables for schema_registry
I use the following configuration under config key:
```
schema_registry.schemas.avro_schema_eventkey {
  type = "avro" 
  source = "my_source"
  description = "Schema"
}
```

That works fine, however I have multi envs and `schema_registry.schemas.avro_schema_eventkey.source` must be overwritten by env variables.

I tried to use the following:
```
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: {{ include "emqx-operator-crd.fullname" . }}
  labels:
     {{- include "emqx-operator-crd.labels" . | nindent 4 }}
spec:
  coreTemplate:
    spec: 
      env:
        - name: EMQX_SCHEMA_REGISTRY__SCHEMAS__AVRO_SCHEMA_EVENTKEY__SOURCE
          value:  "my_value"
 ```         
Getting error:
`│ 2023-10-17T21:09:30.452886+00:00 [error] #{kind => validation_error,matched_type => "avro",path => "schema_registry.schemas.avro_schema_eventkey.source",reason => required_field`

Keep in mind that I still keep the schema_registry config under config key but without the source, so:
```
schema_registry.schemas.avro_schema_eventkey {
  type = "avro" 
  description = "Schema"
}
```

Something similar works for auth and bridges but doesn't work for schema_registry. 

Any ideas why is that?
