### DISCUSSION TITLE
How the persistence work on EMQX?

### DISCUSSION THREAD

**Discussion by badsector3** [emqx/emqx-operator#980] [Q&A]
Hi.

   I have one core node of EMQX with persistent EFS volume attached to the node (AWS). I use Kafka bridge integration.  
```
  coreTemplate:
    spec: 
      replicas: 1
      volumeClaimTemplates:
        storageClassName: emqx-storage-class
        volumeMode: Filesystem
        resources:
          requests:
            storage: 20Gi
        accessModes:
          - ReadWriteMany
```

For the test, I removed access from EMQX -> Kafka, so I could see 25 massages in the queue. 
Then I restarted the pod and re-establish the connection back from EMQX to  Kafka.
I would expect the messages to be sent and appear in the Kafka topic, but that was not the outcome.

Should the messages be dropped on the EFS while in queue? What do I miss here?
