### ISSUE TITLE
PVC is not deleted When Cluster is deleted.

### ISSUE THREAD

**Issue by IBeyondy** [emqx/emqx-operator#1048]
**Describe the bug**
PVC is not deleted when emqx cluster is deleted.

**To Reproduce**
- Create EMQX Cluster 
```
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
   name: emqx-ee
spec:
   image: emqx/emqx-enterprise:5.6
```

- Delete EMQX Cluster
```shell

kubectl delete emqx emqx-ee

```

- All Resource but PVC is deleted

<img width="1120" alt="CleanShot 2024-04-25 at 18 06 49@2x" src="https://github.com/emqx/emqx-operator/assets/9834483/9dd9d6a8-39d9-4d74-8707-d3c488b590eb">

**Expected behavior**

All Resource related to Cluster need to be cleared. 

**Anything else we need to know?**:

**Environment details:**:
- Kubernetes version:   kubernetes 1.20 +
- Cloud-provider/provisioner:
- emqx-operator version: latest version.
- Install method: e.g. helm/static manifests
