### ISSUE TITLE
emqx-operator-controller-manage panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zhengbucuo** [emqx/emqx-operator#1053]
**Describe the bug**
emqx-operator-controller-manage bug logs
```logs
[A clear and concise description of what the bug is.](panic: runtime error: invalid memory address or nil pointer dereference)
I0518 03:46:05.103821       1 leaderelection.go:250] attempting to acquire leader lease emqx-operator-system/19fd6fcc.emqx.io...
{"level":"info","ts":"2024-05-18T03:46:05Z","logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":"2024-05-18T03:46:05Z","logger":"controller-runtime.webhook","msg":"Serving webhook server","host":"","port":9443}
{"level":"info","ts":"2024-05-18T03:46:05Z","logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
I0518 03:46:36.328989       1 leaderelection.go:260] successfully acquired lease emqx-operator-system/19fd6fcc.emqx.io
{"level":"info","ts":"2024-05-18T03:46:36Z","msg":"Starting EventSource","controller":"emqxbroker","controllerGroup":"apps.emqx.io","controllerKind":"EmqxBroker","source":"kind source: *v1beta4.EmqxBroker"}
{"level":"info","ts":"2024-05-18T03:46:36Z","msg":"Starting Controller","controller":"emqxbroker","controllerGroup":"apps.emqx.io","controllerKind":"EmqxBroker"}
{"level":"info","ts":"2024-05-18T03:46:36Z","msg":"Starting EventSource","controller":"emqxplugin","controllerGroup":"apps.emqx.io","controllerKind":"EmqxPlugin","source":"kind source: *v1beta4.EmqxPlugin"}
{"level":"info","ts":"2024-05-18T03:46:36Z","msg":"Starting Controller","controller":"emqxplugin","controllerGroup":"apps.emqx.io","controllerKind":"EmqxPlugin"}
{"level":"info","ts":"2024-05-18T03:46:36Z","msg":"Starting EventSource","controller":"emqxenterprise","controllerGroup":"apps.emqx.io","controllerKind":"EmqxEnterprise","source":"kind source: *v1beta4.EmqxEnterprise"}
{"level":"info","ts":"2024-05-18T03:46:36Z","msg":"Starting Controller","controller":"emqxenterprise","controllerGroup":"apps.emqx.io","controllerKind":"EmqxEnterprise"}
{"level":"info","ts":"2024-05-18T03:46:36Z","msg":"Starting EventSource","controller":"rebalance","controllerGroup":"apps.emqx.io","controllerKind":"Rebalance","source":"kind source: *v2beta1.Rebalance"}
{"level":"info","ts":"2024-05-18T03:46:36Z","msg":"Starting Controller","controller":"rebalance","controllerGroup":"apps.emqx.io","controllerKind":"Rebalance"}
{"level":"info","ts":"2024-05-18T03:46:36Z","msg":"Starting EventSource","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","source":"kind source: *v2beta1.EMQX"}
{"level":"info","ts":"2024-05-18T03:46:36Z","msg":"Starting Controller","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX"}
{"level":"info","ts":"2024-05-18T03:46:36Z","msg":"Starting workers","controller":"emqxbroker","controllerGroup":"apps.emqx.io","controllerKind":"EmqxBroker","worker count":1}
{"level":"info","ts":"2024-05-18T03:46:36Z","msg":"Starting workers","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","worker count":1}
{"level":"info","ts":"2024-05-18T03:46:36Z","msg":"Starting workers","controller":"rebalance","controllerGroup":"apps.emqx.io","controllerKind":"Rebalance","worker count":1}
{"level":"info","ts":"2024-05-18T03:46:36Z","msg":"Starting workers","controller":"emqxplugin","controllerGroup":"apps.emqx.io","controllerKind":"EmqxPlugin","worker count":1}
{"level":"info","ts":"2024-05-18T03:46:36Z","msg":"Starting workers","controller":"emqxenterprise","controllerGroup":"apps.emqx.io","controllerKind":"EmqxEnterprise","worker count":1}
{"level":"info","ts":"2024-05-18T03:46:37Z","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"emqx","controllerGroup":"apps.emqx.io","controllerKind":"EMQX","EMQX":{"name":"emqx","namespace":"emqx-operator-system"},"namespace":"emqx-operator-system","name":"emqx","reconcileID":"da3df036-b355-45d3-9f11-823ed8fd876c"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x1752680]

goroutine 206 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:116 +0x1e5
panic({0x192fec0?, 0x2bac780?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/emqx/emqx-operator/controllers/apps/v2beta1.(*updateStatus).reconcile(0xc000480118, {0x1e3de08, 0xc0002004e0}, {{0xc000158900?, 0xc000472000?}, 0xc0002004e0?}, 0xc000472000, {0x1e3eaa0, 0xc0019c8580})
	/workspace/controllers/apps/v2beta1/update_emqx_status.go:122 +0x860
github.com/emqx/emqx-operator/controllers/apps/v2beta1.(*EMQXReconciler).Reconcile(0xc00041c030, {0x1e3de08, 0xc0002004e0}, {{{0xc00019b620?, 0x5?}, {0xc0006699bc?, 0xc00073dd08?}}})
	/workspace/controllers/apps/v2beta1/emqx_controller.go:137 +0x7d7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1e40e98?, {0x1e3de08?, 0xc0002004e0?}, {{{0xc00019b620?, 0xb?}, {0xc0006699bc?, 0x0?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:119 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0000e77c0, {0x1e3de40, 0xc0005765a0}, {0x19df880?, 0xc000464fe0?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:316 +0x3cc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000e77c0, {0x1e3de40, 0xc0005765a0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266 +0x1af
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 136
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:223 +0x565
```
**To Reproduce**
Updating kind: EMQX configuration will reproduce, replicates: 3 cannot be restored.

**Expected behavior**
Normal operation, can update kind: EMQX yaml

**Anything else we need to know?**:

- kind: EMQX yaml
```yaml
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: emqx-operator-system
spec:
  image: "emqx:latest"
  coreTemplate:
    spec:
      replicas: 3
      resources:
        requests:
          memory: 2Gi
      volumeClaimTemplates:
        storageClassName: alibabacloud-cnfs-nas
        resources:
          requests:
            storage: 500Gi
        accessModes:
          - ReadWriteOnce
  dashboardServiceTemplate:
    spec:
      type: NodePort
  listenersServiceTemplate:
    metadata:
      annotations:
        service.beta.kubernetes.io/alibaba-cloud-loadbalancer-force-override-listeners: 'true'
        service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: "nlb-96k7s0t69wqxq17vsw"
        service.beta.kubernetes.io/alibaba-cloud-loadbalancer-cert-id: "12354626-cn-hangzhou"
        service.beta.kubernetes.io/alibaba-cloud-loadbalancer-protocol-port: "tcpssl:30883"
    spec:
      type: LoadBalancer
      loadBalancerClass: "alibabacloud.com/nlb"
      ports:
        - name: tcpssl
          port: 30883
          protocol: TCP
          targetPort: 1883
  updateStrategy:
    evacuationStrategy:
      waitTakeover: 10
    initialDelaySeconds: 10
    type: Recreate
```
**Environment details:**:
- Kubernetes version: 1.28
- Cloud-provider/provisioner: aliyun ack
- emqx-operator version:  emqx/emqx-operator-controller:2.2.22
- Install method: helm
