### ISSUE TITLE
EMQX_AUTHENTICATION will print out password in plain text in kubernetes container logs

### ISSUE THREAD

**Issue by JonSchaeffer** [emqx/emqx-operator#1060]
**Describe the bug**
When setting the EMQX_AUTHENTICATION environment variable through a secret using `envFromSecret`, the container logs for EMQX will print out the password set under EMQX_AUTHENTICATION in plain text. 

**To Reproduce**
Create a Kubernetes secret that follows the JSON format for EMQX_AUTHENTICATION. 
`[{"backend":"postgresql","database":"database","enable":true,"mechanism":"password_based","password":"test123!","password_hash_algorithm":{"name":"encryption_name"},"pool_size":8,"query":"SELECT \"tokenHash\" as \"password_hash\" FROM \"Table\" where \"id\" = ${username} and \"deletedAt\" is NULL LIMIT 1","server":"cloud-sql-proxy.default.svc.cluster.local","username":"emqx"}]`

Then start up EMQX and check the logs to see JSON printed out with the `password` printed in plain text.

**Expected behavior**
I would expect EMQX to print out the env var with the password starred out like this: 

`EMQX_AUTHENTICATION [authentication]: [#{<<"backend">> => <<"postgresql">>,<<"database">> => <<"database">>,<<"enable">> => true,<<"mechanism">> => <<"password_based">>,<<"password">> => <<*****>>,<<"password_hash_algorithm">> => #{<<"name">> => <<"encryption_name">>},<<"pool_size">> => 8,<<"query">> => <<"SELECT \"tokenHash\" as \"password_hash\" FROM \"table\" where \"id\" = ${username} and \"deletedAt\" is NULL LIMIT 1">>,<<"server">> => <<"cloud-sql-proxy.default.svc.cluster.local">>,<<"username">> => <<"emqx">>}]`

**Anything else we need to know?**:

Additionally, it would be nice to be able to define the password from a secretKeyRef under `emqxConfig` like proposed below

```
emqxConfig:
    authentication:
      - mechanism: password_based
        enable: true
        backend: postgresql
        password_hash_algorithm:
          name: encryption_name
        query: 'SELECT "tokenHash" as "password_hash" FROM "table" where "id" = ${username} and "deletedAt" is NULL LIMIT 1'
        server: postgres
        database: database
        pool_size: 8
        username: emqx
        password:
        valueFrom:
          secretKeyRef:
            name: "emqx-exhibit-management-authentication-password"
            key: password
```

**Environment details:**:
- Kubernetes version: 1.28.8+k3s1
- Cloud-provider/provisioner: Locally with Tilt
- emqx-operator version: 5.7.0
- Install method: helm
