### ISSUE TITLE
Unable to change the service name for the Listener Service

### ISSUE THREAD

**Issue by hardillb** [emqx/emqx-operator#1078]
**Describe the bug**

Setting `metadata.name` in the `listenersServiceTemplate` doesn't change the service name

```
  listenersServiceTemplate:
    metadata:
      name: mqtt-service
    spec:
      type: LoadBalancer
```

**To Reproduce**

- Install the operator
- create a new broker with `name` entry in `metadata` section of `listenersServiceTemplate`

**Expected behavior**
The ability to rename the listeners service

**Anything else we need to know?**:

**Environment details:**:
- Kubernetes version: 1.24
- Cloud-provider/provisioner: microK8s 
- emqx-operator version: 2.2.24
- Install method: helm

**Comment by Rory-Z** [comment]
Hi @hardillb EMQX operator did this on purpose, like the `.spec.template.metadata` in deployment.

**Comment by hardillb** [comment]
If there are `metadata` fields that can not be set/overridden then they should be documented. At the moment the docs imply that any `metadata`can be set.

Is there a way to get a different service name? This makes it very hard to use emqx as a drop in replacement for an existing broker.

**Comment by hardillb** [comment]
OK, so I've worked out that the services are all prefixed with the `metadata.name` from the `emqx` object which sort of makes sense, but it would be nice to also have custom names.

Also it would be nice to be able to mark some listeners as not exported to the LoadBalancer, but still available internally (but this is a separate feature request).

**Comment by Rory-Z** [comment]
> OK, so I've worked out that the services are all prefixed with the metadata.name from the emqx object which sort of makes sense, but it would be nice to also have custom names.

Yes, and also you can set custom labels for different service, is it make sense for you ?

**Comment by Rory-Z** [comment]
> Also it would be nice to be able to mark some listeners as not exported to the LoadBalancer, but still available internally (but this is a separate feature request).

Could you please talk this feature request ? Is it means you want to set some EMQX's listener, but you don't want to export it to K8s service ? I have some confuse, because in K8s, the best way to access pod's port is by service, because pod is not a stateful object, it will be re-scheduling in anytime.

**Comment by hardillb** [comment]
> Yes, and also you can set custom labels for different service, is it make sense for you ?

Can you point to the documentation for that please.

> Could you please talk this feature request ? Is it means you want to set some EMQX's listener, but you don't want to export it to K8s service ? 

I mean that I want to expose some listeners outside of k8s via a LoadBalancer service and. Some just internally say via a ClusterIP service.

E.g. I want to make just a TLS listener available to external clients, but provide a none TLS listener to clients inside the cluster

**Comment by Rory-Z** [comment]
> > Yes, and also you can set custom labels for different service, is it make sense for you ?
>
> Can you point to the documentation for that please.

Like this:
```yaml
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: emqx:5
  listenersServiceTemplate:
    metadata:
      labels:
        my-service: "my-listeners-service"
  dashboardServiceTemplate:
    metadata:
      labels:
        my-service: "my-dashboard-service"
```

And then, you can get service by kubectl
```bash
$ kubectl get svc -l 'my-service=my-listeners-service'
NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                               AGE
emqx-listeners   ClusterIP   10.101.163.27   <none>        8883/TCP,1883/TCP,8083/TCP,8084/TCP   35s
```

```bash
$ kubectl get svc -l 'my-service=my-dashboard-service'
NAME             TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)     AGE
emqx-dashboard   ClusterIP   10.98.60.14   <none>        18083/TCP   40s
```
