### ISSUE TITLE
aws eks

### ISSUE THREAD

**Issue by joehecn** [emqx/emqx-operator#119]
按照用户说明操作在 aws(亚马逊中国宁夏区) eks 集群上跑不起来，
请问能不能提供一个在eks上运行的 demo
```bash
NAME     READY   STATUS             RESTARTS   AGE    IP               NODE                                                NOMINATED NODE   READINESS GATES
emqx-0   0/1     CrashLoopBackOff   3          112s   192.168.75.204   ip-192-168-88-157.cn-northwest-1.compute.internal   <none>           <none>
emqx-1   0/1     Error              4          112s   192.168.24.100   ip-192-168-21-143.cn-northwest-1.compute.internal   <none>           <none>
emqx-2   0/1     CrashLoopBackOff   3          112s   192.168.39.78    ip-192-168-50-143.cn-northwest-1.compute.internal   <none>           <none>
emqx-0   0/1     Running            4          2m1s   192.168.75.204   ip-192-168-88-157.cn-northwest-1.compute.internal   <none>           <none>
emqx-1   0/1     CrashLoopBackOff   4          2m4s   192.168.24.100   ip-192-168-21-143.cn-northwest-1.compute.internal   <none>           <none>
emqx-0   0/1     Error              4          2m5s   192.168.75.204   ip-192-168-88-157.cn-northwest-1.compute.internal   <none>           <none>
emqx-2   0/1     Running            4          2m6s   192.168.39.78    ip-192-168-50-143.cn-northwest-1.compute.internal   <none>           <none>
emqx-2   0/1     Error              4          2m11s   192.168.39.78    ip-192-168-50-143.cn-northwest-1.compute.internal   <none>           <none>
emqx-0   0/1     CrashLoopBackOff   4          2m16s   192.168.75.204   ip-192-168-88-157.cn-northwest-1.compute.internal   <none>           <none>
```

```bash
Events:
  Type     Reason                  Age                     From                     Message
  ----     ------                  ----                    ----                     -------
  Normal   Scheduled               7m33s                   default-scheduler        Successfully assigned default/emqx-1 to ip-192-168-21-143.cn-northwest-1.compute.internal
  Normal   SuccessfulAttachVolume  7m31s                   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-ba0d0dbc-7251-4f37-a6de-e493eafe6a26"
  Normal   SuccessfulAttachVolume  7m31s                   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-08f7c78e-e0e7-4b28-a64c-d7362c96fa95"
  Normal   Pulled                  5m48s (x5 over 7m28s)   kubelet                  Container image "emqx/emqx:4.4.1" already present on machine
  Normal   Created                 5m48s (x5 over 7m28s)   kubelet                  Created container emqx
  Normal   Started                 5m48s (x5 over 7m28s)   kubelet                  Started container emqx
  Warning  Unhealthy               5m43s (x3 over 7m23s)   kubelet                  Readiness probe failed: Get "http://192.168.24.100:8081/status": dial tcp 192.168.24.100:8081: connect: connection refused
  Warning  BackOff                 2m22s (x22 over 7m17s)  kubelet                  Back-off restarting failed container
```

**Comment by Rory-Z** [comment]
Hi，@joehecn
看起来是 pod 启动失败了，请提供一下 pod 的日志，谢谢

**Comment by joehecn** [comment]
Hi, @Rory-Z 
谢谢回复，Pod日志如下：
hemiao@hemiaodeMacBook-Pro ~ % kubectl logs emqx-0
2022-02-22T21:51:05.098179+00:00 [error] Error creating /opt/emqx/data/configs: permission denied

hemiao@hemiaodeMacBook-Pro ~ % kubectl logs emqx-1
2022-02-22T21:51:10.674292+00:00 [error] Error creating /opt/emqx/data/configs: permission denied

hemiao@hemiaodeMacBook-Pro ~ % kubectl logs emqx-2
2022-02-22T21:51:38.581910+00:00 [error] Error creating /opt/emqx/data/configs: permission denied

**Comment by Rory-Z** [comment]
@joehecn 看起来是权限问题，请分享一下你用于部署的 emqx.yaml ，以及 `kubectl get storageclass` 命令的输出

**Comment by joehecn** [comment]
``` bash
$ kubectl get storageclass
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2 (default)   kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  2d16h
```
emqx.yaml
``` yaml
## full example
apiVersion: apps.emqx.io/v1beta1
kind: EmqxBroker
metadata:
  name: emqx
  labels:
    cluster: emqx
spec:
  serviceAccountName: emqx
  image: emqx/emqx:4.4.1
  replicas: 3
  labels:
    cluster: emqx
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: gp2
        resources:
          requests:
            storage: 20Mi
        accessModes:
          - ReadWriteOnce
  env:
    - name: "EMQX_LOG__LEVEL"
      value: "debug"
  listener:
    type: ClusterIP
    ports:
      mqtt: 1883
      mqtts: 8883
      ws: 8083
      wss: 8084
      dashboard: 18083
      api: 8081
  acl:
    - permission: allow
      username: "dashboard"
      action: subscribe
      topics:
        filter:
          - "$SYS/#"
          - "#"
    - permission: allow
      ipaddress: "127.0.0.1"
      topics:
        filter:
          - "$SYS/#"
        equal:
          - "#"
    - permission: deny
      action: subscribe
      topics:
        filter:
          - "$SYS/#"
        equal:
          - "#"
    - permission: allow
  plugins:
    - name: emqx_management
      enable: true
    - name: emqx_recon
      enable: true
    - name: emqx_retainer
      enable: true
    - name: emqx_dashboard
      enable: true
    - name: emqx_telemetry
      enable: true
    - name: emqx_rule_engine
      enable: true
    - name: emqx_bridge_mqtt
      enable: false
  modules:
    - name: emqx_mod_acl_internal
      enable: true
    - name: emqx_mod_presence
      enable: true
```
