### ISSUE TITLE
[Question] reason behind changing accessModes from ReadWriteOnce in v1beta1 sample to ReadWriteMany in v1beta2 sample

### ISSUE THREAD

**Issue by uqix** [emqx/emqx-operator#124]
in [v1beta](https://github.com/emqx/emqx-operator/blob/main/config/samples/emqx/v1beta1/emqx.yaml) sample:
```yaml
spec:
  serviceAccountName: emqx
  image: emqx/emqx:4.3.11
  replicas: 3
  labels:
    cluster: emqx
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: standard
        resources:
          requests:
            storage: 20Mi
        accessModes:
        - ReadWriteOnce
```

in [v1beta2](https://github.com/emqx/emqx-operator/blob/main/docs/user-guides/get-started.md) sample:

```yaml
spec:
  serviceAccountName: "emqx"
  image: emqx/emqx:4.3.11
  replicas: 3
  labels:
    cluster: emqx
  storage:
    storageClassName: standard
    resources:
      requests:
        storage: 20Mi
    accessModes:
    - ReadWriteMany
```
