### ISSUE TITLE
Service creation fails

### ISSUE THREAD

**Issue by ammmze** [emqx/emqx-operator#164]
**Describe the bug**
I'm getting the following error when attempting deploy an `EmqxBroker`:
```
1.647123650787955e+09    ERROR    controller.emqxbroker    Reconciler error    {"reconciler group": "apps.emqx.io", "reconciler kind": "EmqxBroker", "name": "emqx2", "namespace": "home-iot", "error": "Service \"emqx2\" is invalid: spec.ports: Required value"}
```
The service does not get created, nor does the statefulset. I do see the headless service get created, but no ports are on it.

**To Reproduce**
Here's the resource I am applying (note: I'm using Flux CD which replaces things like `${SECRET_CLUSTER_DOMAIN}`):

```yaml
---
apiVersion: apps.emqx.io/v1beta2
kind: EmqxBroker
metadata:
  name: &name emqx2
  namespace: home-iot
spec:
  image: emqx/emqx:4.4.0
  replicas: 3
  labels:
    cluster: *name
  env:
    - name: EMQX_ALLOW_ANONYMOUS
      value: 'true'
    - name: EMQX_ADMIN_PASSWORD
      value: "${SECRET_EMQX_ADMIN_PASSWORD}"
    - name: EMQX_AUTH__MNESIA__PASSWORD_HASH
      value: sha256
    - name: EMQX_AUTH__USER__1__USERNAME
      value: "${SECRET_MQTT_USERNAME}"
    - name: EMQX_AUTH__USER__1__PASSWORD
      value: "${SECRET_MQTT_PASSWORD}"
  storage:
    storageClassName: rook-ceph-block
    resources:
      requests:
        storage: 20Mi
    accessModes:
      - ReadWriteOnce
  emqxTemplate:
    listener:
      type: LoadBalancer
      loadBalancerIP: 192.168.69.61
      ports:
        mqtt: 1883
        mqtts: 8883
        ws: 8083
        wss: 8084
        dashboard: 18083
        api: 8081
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "mqtt2.${SECRET_CLUSTER_DOMAIN}"
        coredns.io/hostname: "mqtt2.${SECRET_CLUSTER_DOMAIN}"
    acl:
      - permission: allow
        username: "dashboard"
        action: subscribe
        topics:
          filter:
            - "$SYS/#"
            - "#"
      - permission: allow
        ipaddress: "127.0.0.1"
        topics:
          filter:
            - "$SYS/#"
          equal:
            - "#"
      - permission: deny
        action: subscribe
        topics:
          filter:
            - "$SYS/#"
          equal:
            - "#"
      - permission: allow
    plugins:
      - name: emqx_management
        enable: true
      - name: emqx_recon
        enable: true
      - name: emqx_retainer
        enable: true
      - name: emqx_dashboard
        enable: true
      - name: emqx_telemetry
        enable: true
      - name: emqx_rule_engine
        enable: true
      - name: emqx_bridge_mqtt
        enable: false
    modules:
      - name: emqx_mod_acl_internal
        enable: true
      - name: emqx_mod_presence
        enable: true
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: apps.emqx.io/instance
                  operator: In
                  values:
                    - *name
            topologyKey: kubernetes.io/hostname
```

**Expected behavior**
Broker and service gets created.

**Anything else we need to know?**:
Full logs:
```
1.6471236501591592e+09    INFO    emqx-controller    Reconciling    {"Request.Namespace": "home-iot", "Request.Name": "emqx2"}
1.6471236503776915e+09    ERROR    emqx-controller    crate resource failed    {"groupVersionKind": "/v1, Kind=Service", "namespace": "home-iot", "name": "emqx2", "error": "Service \"emqx2\" is invalid: spec.ports: Required value"}
github.com/emqx/emqx-operator/controllers/apps.(*Handler).createOrUpdate
    /workspace/controllers/apps/ensure.go:54
github.com/emqx/emqx-operator/controllers/apps.(*Handler).Ensure
    /workspace/controllers/apps/ensure.go:25
github.com/emqx/emqx-operator/controllers/apps.(*Handler).Do
    /workspace/controllers/apps/handler.go:53
github.com/emqx/emqx-operator/controllers/apps.(*Handler).Reconcile
    /workspace/controllers/apps/reconcile.go:99
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
1.6471236503984983e+09    ERROR    emqx-controller    Reconcile handler    {"Request.Namespace": "home-iot", "Request.Name": "emqx2", "error": "Service \"emqx2\" is invalid: spec.ports: Required value"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
1.6471236503985639e+09    ERROR    controller.emqxbroker    Reconciler error    {"reconciler group": "apps.emqx.io", "reconciler kind": "EmqxBroker", "name": "emqx2", "namespace": "home-iot", "error": "Service \"emqx2\" is invalid: spec.ports: Required value"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227

```

**Environment details:**:
- Kubernetes version: 1.22.4
- Cloud-provider/provisioner: Baremetal machines running on Talos OS
- emqx-operator version: 1.1.5
- Install method: e.g. helm/static manifests: Operator is installed as a Helm release. The Broker is a static manifest.
