### ISSUE TITLE
podAnnotations not working

### ISSUE THREAD

**Issue by neiledgar** [emqx/emqx-operator#376]
**Describe the bug**
I am trying to apply some pod annotations to the controller manager. My values contains 
```
podAnnotations:
  ad.datadoghq.com/manager.tags: |
    {"env":"dev","service":"operator","version":"2.0.0"}

```

**To Reproduce**
I get an YAML parse error with version emqx-operator 2.0.0, helm v3.7.2, kubectl 1.22.0
`
Error: YAML parse error on emqx-operator/templates/controller-manager.yaml: error converting YAML to JSON: yaml: line 26: did not find expected key
helm.go:88: [debug] error converting YAML to JSON: yaml: line 26: did not find expected key
YAML parse error on emqx-operator/templates/controller-manager.yaml
`

It would appear that the indentation on the line https://github.com/emqx/emqx-operator/blob/main/deploy/charts/emqx-operator/templates/controller-manager.yaml#L32 is incorrect. The output produced is 
```
  template:
    metadata:
        annotations:
        ad.datadoghq.com/haproxy.tags:
          env: dev
          service: operator
          version: 2.0.0
```
I would expect 
```
  template:
    metadata:
      annotations:
        ad.datadoghq.com/haproxy.tags:
          env: dev
          service: operator
          version: 2.0.0
```
