### ISSUE TITLE
Permission denied error when uncommenting `volumeClaimTemplates`

### ISSUE THREAD

**Issue by daadu** [emqx/emqx-operator#383]
**Describe the bug**
I have configured `EMQX` as following

```yaml
    apiVersion: apps.emqx.io/v2alpha1
    kind: EMQX
    metadata:
      name: emqx
    spec:
      image: emqx/emqx:5.0.6
      coreTemplate:
        metadata:
          name: emqx-core
          labels:
            apps.emqx.io/instance: emqx
            apps.emqx.io/db-role: core
          annotations:
        spec:
          replicas: 1
          volumeClaimTemplates:
            resources:
              requests:
                storage: 1Gi
            accessModes:
              - ReadWriteOnce
          ports:
            - containerPort: 1883
          envFrom:
            - prefix: EMQX_
              configMapRef:
                name: emqx-config
            - prefix: EMQX_AUTHENTICATION__0__
              secretRef:
                name: emqx-pgsql-connection
            - prefix: EMQX_AUTHORIZATION__SOURCES__0__
              secretRef:
                name: emqx-pgsql-connection
          resources:
            limits:
              # cpu: 100m
              memory: 256Mi
            # requests:
            #   cpu: 100m
            #   memory: 256Mi
      dashboardServiceTemplate:
        metadata:
          name: emqx-dashboard
        spec:
          selector:
            apps.emqx.io/db-role: core
          ports:
            - name: "dashboard-listeners-http-bind"
              protocol: TCP
              port: 18083
              targetPort: 18083
      listenersServiceTemplate:
        metadata:
          name: emqx-listeners
        spec:
          ports:
            - name: "tcp-default"
              protocol: TCP
              port: 1883
              targetPort: 1883
```

When the `emqx-core-0` starts it crashes with following error:

```
mkdir: cannot create directory ‘/opt/emqx/data/configs’: Permission denied                                                                │
│ Stream closed EOF for my-namespace/emqx-core-0 (emqx)      
```

**To Reproduce**
I just uncommented `volumeClaimTemplates` section under `coreTemplate` [also removed hardcoded `storageClassName` so that the default is selected] - removed `replicantTemplate` section, as not required - removed commented code

**Expected behavior**
This error should not come when using "sample" config values. 

Not sure, how to fix this - looks like the pod has no write permission on volume mounted - either it controller has bug or config is wrong.

**Environment details:**:
- Kubernetes version: 1.23.10
- Cloud-provider/provisioner: Linode
- emqx-operator version:  2.0.0
- Install method: Helm + Helmfile
