### ISSUE TITLE
how to modify host 

### ISSUE THREAD

**Issue by happyi** [emqx/emqx-operator#776]
```
EMQX_HOST: $(POD_NAME).$(STS_HEADLESS_SERVICE_NAME).$(POD_NAMESPACE).svc.cluster.local
```
this is  the operator generated 

however my domain of k8s is  k8s.com  not  cluster.local

**Comment by Gala-R** [comment]
> 

I am very sorry that this field is temporarily not allowed to be modified, we will solve your problem in the next version

**Comment by Gala-R** [comment]
> ```
> EMQX_HOST: $(POD_NAME).$(STS_HEADLESS_SERVICE_NAME).$(POD_NAMESPACE).svc.cluster.local
> ```
> 
> this is the operator generated
> 
> however my domain of k8s is k8s.com not cluster.local

I am very sorry that this field is temporarily not allowed to be modified, we will solve your problem in the next version

**Comment by Gala-R** [comment]
> ```
> EMQX_HOST: $(POD_NAME).$(STS_HEADLESS_SERVICE_NAME).$(POD_NAMESPACE).svc.cluster.local
> ```
> 
> this is the operator generated
> 
> however my domain of k8s is k8s.com not cluster.local

What version of emqx do you use?

**Comment by Rory-Z** [comment]
> however my domain of k8s is k8s.com not cluster.local

Sorry, can not modify this for now, we will support modify it in next release

**Comment by Rory-Z** [comment]
> Sorry, can not modify this for now, we will support modify it in next release

Hi, @happyi Sorry my bad, I think you can set env for `EMQX_HOST` like this:

```
apiVersion: apps.emqx.io/v2alpha1
kind: EMQX
metadata:
  name: emqx
spec:
  image: emqx:5.0
  coreTemplate:
    spec:
      env:
      - name: EMQX_HOST
         value: "$(POD_NAME).$(STS_HEADLESS_SERVICE_NAME).$(POD_NAMESPACE).svc.k8s.com"
  replicantTemplate:
    spec:
      env:
      - name: EMQX_HOST
         value: "$(POD_NAME).$(STS_HEADLESS_SERVICE_NAME).$(POD_NAMESPACE).svc.k8s.com"
```
