### ISSUE TITLE
No Loadbalancer is created for 5.1.0 

### ISSUE THREAD

**Issue by fabltd** [emqx/emqx-operator#820]
Help

The operator appears not to work for 5.1.0 and no loadbalancer is created

**Comment by fabltd** [comment]
The emqx-replicant and ingress loadbalancer are not created any longer. This is now unusable with the current version

**Comment by Rory-Z** [comment]
Hi, @fabltd Sorry the EMQX Operator 2.1 doesn't compatible EMQX 5.1, it just can install EMQX 5.0.

In EMQX 5.1, the EMQX development team introduced some break changes, so EMQX Operator 2.1 cannot support it perfectly. We are currently developing EMQX Operator 2.2.

**Comment by Rory-Z** [comment]
Some simple modifications to the EMXQ custom resources may allow you to deploy EMQX 5.1 through EMQX Operator 2.1:

1. add `env[].name: EMQX_API_KEY__BOOTSTRAP_FILE` and `env[].value: '"/opt/emqx/data/bootstrap_user"'` for `.spec.coreTemplate.spec`, please note the single and double quotes of the value of environment variables.
2. Manually add the ports you want to listen to in `listenersServiceTemplate`, just like k8s service resources.

**Comment by fabltd** [comment]
Hi sorry where do I add the example. Can you show me a code snippet as to where to install?

**Comment by Rory-Z** [comment]
Sure, the example like this:
```
apiVersion: apps.emqx.io/v2alpha1
kind: EMQX
metadata:
    name: emqx
# Core
spec:
    image: emqx/emqx:5.1.0
    coreTemplate:
      metadata:
        name: emqx-core
        labels:
          apps.emqx.io/instance: emqx
          apps.emqx.io/db-role: core
        annotations:
      spec:
        env:
        - name: EMQX_API_KEY__BOOTSTRAP_FILE
          value: '"/opt/emqx/data/bootstrap_user"'
        podSecurityContext:
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
              fsGroupChangePolicy: Always
              supplementalGroups:
                - 1000
        volumeClaimTemplates:
            #storageClassName: standard-rwo
            resources:
              requests:
                storage: 1Gi
            accessModes:
              - ReadWriteOnce
        replicas: 3
# BootStrap Config
    bootstrapConfig: |
        dashboard {
          default_username: "admin"
          default_password: "public"
        }
# Dashboard
    dashboardServiceTemplate:
      metadata:
        name: emqx-dashboard
      spec:
        type: NodePort
        selector:
          apps.emqx.io/db-role: core
        ports:
          - name: "dashboard-listeners-http-bind"
            protocol: TCP
            port: 18083
            targetPort: 18083
            nodePort: 30008
# Listeners
    listenersServiceTemplate:
      metadata:
        name: emqx-listeners
      spec:
        type: LoadBalancer
        sessionAffinity: ClientIP
        ports:
        - name: tcp-default
          port: 1883
          protocol: TCP
          targetPort: 1883
        - name: ssl-default
          port: 8883
          protocol: TCP
          targetPort: 8883
        - name: ws-default
          port: 8083
          protocol: TCP
          targetPort: 8083
        - name: wss-default
          port: 8084
          protocol: TCP
          targetPort: 8084
```
