### ISSUE TITLE
How to add custom ENV in CRD EmqxBroker

### ISSUE THREAD

**Issue by rjbaat** [emqx/emqx-operator#88]
Hi,
How can I add extra ENV in the EmqxBroker yaml config?
So I can enable the mysql auth plugin and setup the right settings. 
Should I do that with ENV or is there another way to add the configs related to the plugin?

@Rory-Z can you maybe help me out with a sample config where the emqx mysql auth plugin is added? I tried to get the env somehow in the manifest but I doesn't get it to work.

**Comment by Rory-Z** [comment]
Hi, @rjbaat 
Apologies for the delay reply
Perhaps you could refer to the following example

```
apiVersion: apps.emqx.io/v1beta2
kind: EmqxBroker
metadata:
  name: emqx
spec:
  image: emqx/emqx:4.3.10
  replicas: 3
  emqxTemplate:
    plugins:
      - name: emqx_management
        enable: true
      - name: emqx_auth_mysql
        enable: true
  env:
    - name: EMQX_AUTH__MYSQL__SERVER
      value: 127.0.0.1:3306
    - name: EMQX_AUTH__MYSQL__USERNAME
      value: username
    - name: EMQX_AUTH__MYSQL__PASSWORD
      value: password
    - name: EMQX_AUTH__MYSQL__DATABASE
      value: database
```
