### ISSUE TITLE
Configuration after ungracefully cluster shutdown/restart

### ISSUE THREAD

**Issue by memoliyasti** [emqx/emqx-operator#896]
I would like to hear suggestions about the **EMQX v5.0.16** configuration that I can use for rolling out core/replicants after the ungracefully on-prem cluster shutdown

**EMQX** running on an **on-prem** cluster are not able to scale up/run after ungracefully shutdown. I need to scale down/up again.
I wonder if is there any configuration I can apply on EMQX or best practice I need to follow on the **K8S** cluster?

**Comment by paresh1492** [comment]
> Hello all,
> 
> We have **EMQX** running on an **on-prem** cluster with 3 core 3 replicant pods. On-Prem cluster has 3 masters and 3 worker nodes. Whenever the on-prem cluster has been shut down ungracefully (power outage), EMQX pods are not running properly again. And I need to scale down/up after the ungracefully shutdown. This causes client disconnections and data loss until fixed manually.
> 
> I would like to hear suggestions about the **EMQX v5.0.16** configuration that I can use for rolling out core/replicants after the ungracefully on-prem cluster shutdown
> 
> I wonder if is there any configuration I can apply on EMQX or best practice I need to follow on the **K8S** cluster?
> 
> I am adding the EMQX configuration below.
> 
> ```yaml
> apiVersion: apps.emqx.io/v2alpha1
> kind: EMQX
> metadata:
>   name: emqx
>   namespace: namespace
> spec:
>   image: "image"
>   imagePullSecrets:
>     - name: secret
>   bootstrapConfig: |
>     authorization {
>       no_match = "deny"
>       deny_action = "disconnect"
>       sources = [{type: "file", enable: true, path: "/etc/emqx/acl.conf"}]
>     }
>     dashboard {
>       listeners.http {
>           bind: 18083
>       } 
>     }
>     listeners.tcp.default {
>       bind = "0.0.0.0:1883"
>       max_connections = 1024000
>       acceptors = 256
>     }
>     listeners.tcp.internal {
>       bind = "0.0.0.0:1884"
>       max_connections = 1024000
>       acceptors = 256
>     }
>     listeners.tcp.quic {
>       bind = "0.0.0.0:1885"
>       max_connections = 1024000
>       acceptors = 256
>     }
>     listeners.tcp.external {
>       bind = "0.0.0.0:1886"
>       max_connections = 1024000
>       acceptors = 256
>     }
>     listeners.tcp.api {
>       bind = "0.0.0.0:8083"
>       max_connections = 1024000
>       acceptors = 256
>     }
>     listeners.ssl.mqttssl {
>       bind = "0.0.0.0:8883"
>       max_connections = 1024000
>       acceptors = 256
>     }
>     mqtt {
>     max_inflight = "10000"
>     max_mqueue_len = "7200000"
>     max_packet_size = "25MB"
>     }
> 
>   coreTemplate:
>     metadata:
>       name: emqx-core
>       labels:
>         apps.emqx.io/instance: emqx
>         apps.emqx.io/db-role: core
>     spec:
>       replicas: 3
>       volumeClaimTemplates:
>         storageClassName: {{ .Values.storageClassName }}
>         resources:
>           requests:
>             storage: 4Gi
>         accessModes:
>           - ReadWriteOnce
>       extraVolumes:
>         - name: acl
>           configMap:
>             name: emqx-acl
>       extraVolumeMounts:
>         - name: acl
>           mountPath: "/etc/emqx/acl.conf"
>           subPath: acl.conf
>       resources:
>         requests:
>           memory: "2Gi"
>           cpu: "500m"
>         limits:
>           memory: "2Gi"
>       podSecurityContext:
>         runAsUser: 0
>         runAsGroup: 0
>         fsGroup: 0
>         fsGroupChangePolicy: Always
>       containerSecurityContext:
>         runAsUser: 0
>         runAsGroup: 0
>       livenessProbe:
>         httpGet:
>           path: /status
>           port: 18083
>         initialDelaySeconds: 60
>         periodSeconds: 30
>         failureThreshold: 3
>       readinessProbe:
>         httpGet:
>           path: /status
>           port: 18083
>         initialDelaySeconds: 10
>         periodSeconds: 5
>         failureThreshold: 12
>   replicantTemplate:
>     metadata:
>       name: emqx-replicant
>       labels:
>         apps.emqx.io/instance: emqx
>         apps.emqx.io/db-role: replicant
>     spec:
>       ports:
>         - name: "tcp-replicant"
>           protocol: TCP
>           containerPort: 18083
>       replicas: 3
>       command:
>         - "/usr/bin/docker-entrypoint.sh"
>       args:
>         - "/opt/emqx/bin/emqx"
>         - "foreground"
>       resources:
>         requests:
>           memory: "2Gi"
>           cpu: "500m"
>         limits:
>           memory: "2Gi"
>       extraVolumes:
>         - name: acl
>           configMap:
>             name: emqx-acl
>       extraVolumeMounts:
>         - name: acl
>           mountPath: "/etc/emqx"
>       podSecurityContext:
>         runAsUser: 1000
>         runAsGroup: 1000
>         fsGroup: 1000
>         fsGroupChangePolicy: Always
>         supplementalGroups:
>           - 1000
>       containerSecurityContext:
>         runAsNonRoot: true
>         runAsUser: 1000
>         runAsGroup: 1000
>   listenersServiceTemplate:
>     metadata:
>       name: emqx-listeners
>     spec:
>       ports:
>         - name: "tcp-default"
>           protocol: TCP
>           port: 1883
>           targetPort: 1883
> ```
My emqx cluster is deployed using helm. I set log configuration as per documentation but still logs are not getting stored in file. it gets stored in console. why is that, can anyone please help?

**Comment by Rory-Z** [comment]
@memoliyasti Could you please change EMQX to 5.1.3 and retry it.

**Comment by paresh1492** [comment]
> @memoliyasti Could you please change EMQX to 5.1.3 and retry it.

Is it not possible in version 4.3.5

**Comment by Rory-Z** [comment]
> > @memoliyasti Could you please change EMQX to 5.1.3 and retry it.
> 
> Is it not possible in version 4.3.5

I think your question is not related to the topic of this issue, so it is not suitable to discuss it here. You should create a new issue.

The code of EMQX Helm Chart is in the emqx/emqx repository, which is just the repository for EMQX Operator.

**Comment by Rory-Z** [comment]
> @memoliyasti Could you please change EMQX to 5.1.3 and retry it.

Hi @memoliyasti Is your issue still there?

**Comment by memoliyasti** [comment]
Hi @Rory-Z 

When I wanted to use 5.1.3, replicants did not come up. Issue has not been solved since replicant replicants did not come up. But I think this is related with issue what is mentioned [here](https://github.com/emqx/emqx-operator/issues/905) . It was seeming that creating PVC was blocking for replicants to be deployed. I will try it again after this [merge](https://github.com/emqx/emqx-operator/pull/908)

**Comment by Rory-Z** [comment]
Hi @memoliyasti the EMQX Operator 2.2.1-rc.1 is released,  maybe you can try it

**Comment by memoliyasti** [comment]
Hi @Rory-Z ,

I had a chance to try the new emqx-operator release (2.2.1-rc.1 ) and when I do that with Helm, replicants did not come up but when I try to deploy it as manifest, replicants came up and pvc has been created successfully. 

It seems it is about using Helm. 

Let me share the manifest briefly I used below


```yaml

---
# Source: emqx/templates/configMap.yaml
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: <namespace>
spec:
  image: emqx:5.1.4
  coreTemplate:
    spec:
      replicas: 3
      volumeClaimTemplates:
        storageClassName: "default"
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
  replicantTemplate:
    spec:
      replicas: 3
  listenersServiceTemplate:
    metadata:
      name: emqx-listeners
    spec:
      ports:
        - name: "tcp-default"
          protocol: TCP
          port: 1883
          targetPort: 1883
  dashboardServiceTemplate:
    metadata:
      name: emqx-dashboard
    spec:
      ports:
        - name: "tcp-http"
          protocol: TCP
          port: 18083
          targetPort: 18083
```
