### ISSUE TITLE
Broker cluster never successfully updates after updating operator from 2.1.4 to 2.2.0

### ISSUE THREAD

**Issue by clive-jevons** [emqx/emqx-operator#897]
**Describe the bug**
We have multiple EMQX clusters deployed using the emqx-operator v2.1.4.  
On our DEV cluster I updated the operator to v2.2.0 and watched the Pods. The new STS and Pod for the core node was created (on DEV it's a small broker cluster with only 1 core and 1 replicant). The new core node Pod is created and shows as ready in `kubectl get pod`, but the STS never shows it as ready because the `apps.emqx.io/on-serving` condition is never set (at all).  
When I check the EMQX dashboard I can, however, actually see the new core node and everything looks green there for it. Also, there are no errors in the Pod logs of the new core node.

AFAICT the code which is responsible for creating and then updating that condition (methods `updatePodConditions#reconcile` and `updatePodConditions#checkInCluster`) checks the `.status.coreNodes` field of the `EMQX` resource. When I look at that resource in the cluster, it does _not_ have that field at all.

The original `EMQX` resource was created in version `apps.emqx.io/v2alpha1` but, of course, was updated in-cluster to `apps.emqx.io/v2beta1` during the upgrade of the operator. Not sure if that plays a role.

I haven't looked any deeper into why `status.coreNodes` is missing in the `EMQX` resource yet.

**To Reproduce**
Provision `emqx-operator` in version 2.1.4. Provision a small EMQX broker cluster using API version `apps.emqx.io/v2alpha1`, setting both core and replicants count to 1 and using EMQX image version `emqx:5.0.23`.

Then upgrade the operator to version 2.2.0 and watch the STS and Pods.

**Expected behavior**
Core nodes are updated successfully.

**Anything else we need to know?**:

**Environment details:**:
- Kubernetes version: `v1.24.10`
- Cloud-provider/provisioner: MS AKS
- emqx-operator version: 2.1.4 / 2.2.0
- Install method: Helm

**Comment by Rory-Z** [comment]
Hi， @clive-jevons EMQX Operator 2.2.0 just support EMQX 5.1.1 and later, could you please try upgrade EMQX version and retry

**Comment by clive-jevons** [comment]
Hi @Rory-Z ,
Thanks for the info ... would you recommend first upgrading the broker to 5.1.1 and then the operator to 2.2.0, or the other way round?

**Comment by tollercode** [comment]
Experiencing the same behavior. 

Setup: Operator 2.2.0 + Broker 5.1.1

Readiness probes on core-nodes are failing with connection refused

**Comment by Rory-Z** [comment]
> Experiencing the same behavior.经历同样的行为。
> 
> Setup: Operator 2.2.0 + Broker 5.1.1设置：Operator 2.2.0 + Broker 5.1.1
> 
> Readiness probes on core-nodes are failing with connection refused核心节点上的就绪探测失败，连接被拒绝

Hi @tollercode Could you please change readiness probe and retry it ? It's in `spec.coreTemaplte.spec.readinessProbe`.

If still failed, please show the log of the core pod

**Comment by Rory-Z** [comment]
Hi, @clive-jevons Some `connect: connection refused ` is normal, because the EMQX will restart when it join cluster, could you please tell me more detailed information?

**Comment by tollercode** [comment]
@Rory-Z after editing Readiness-Probe I get following state:

`Corresponding condition of pod readiness gate "apps.emqx.io/on-serving" does not exist`

`EMQX_API_KEY__BOOTSTRAP_FILE [api_key.bootstrap_file]: /opt/emqx/data/bootstrap_api_key
EMQX_RPC__PORT_DISCOVERY [rpc.port_discovery]: manual
EMQX_CLUSTER__DNS__RECORD_TYPE [cluster.dns.record_type]: srv
EMQX_CLUSTER__DNS__NAME [cluster.dns.name]: emqx-cluster-headless.dev.svc.cluster.local
EMQX_CLUSTER__DISCOVERY_STRATEGY [cluster.discovery_strategy]: dns
EMQX_NODE__ROLE [node.role]: core
EMQX_NODE__DATA_DIR [node.data_dir]: dataEMQX_NODE__COOKIE [node.cookie]: ******
EMQX_NODE__NAME [node.name]: emqx@emqx-cluster-core-56db94994-0.emqx-cluster-headless.dev.svc.cluster.local
Listener ssl:default on 0.0.0.0:8883 started.
Listener tcp:default on 0.0.0.0:1883 started.
Listener ws:default on 0.0.0.0:8083 started.
Listener wss:default on 0.0.0.0:8084 started.
Listener http:dashboard on :18083 started.

EMQX Enterprise 5.1.1 is running now!`

**Comment by Rory-Z** [comment]
The readiness gate `apps.emqx.io/on-serving` will be ready after joining the cluster node, you can check EMQX cluster nodes by `emqx ctl cluster status` or `kuebctl get emqx $name -o json | jq .status.coreNodes` and `kuebctl get emqx $name -o json | jq .status.replicantNodes`.
If use EMQX Enterprise,  `apps.emqx.io/on-serving` will also check if `Get api/v5/load_rebalance/availability_check` returns 200.
Could you please check them

**Comment by tollercode** [comment]
@Rory-Z 

Executing this gives:

```
Cluster status: #{running_nodes =>
                      ['emqx@emqx-cluster-core-56db94994-0.emqx-cluster-headless.dev.svc.cluster.local',
                       'emqx@emqx-cluster-core-56db94994-1.emqx-cluster-headless.dev.svc.cluster.local'],
                  stopped_nodes => []}
```

```
NAME           STATUS                 AGE
emqx-cluster   CoreNodesProgressing   11h
```

Calling Get api/v5/load_rebalance/availability_check returns 200 OK. 
Strangely I can also connect to the cluster dashboard and it seems to run fine.

**Comment by Rory-Z** [comment]
@tollercode Could you please open Operator's debug log and share it with me?
you can append `--zap-devel=true` to EMQX Operator container's args, and check EMQX Operator log

And please let me know your EMQX customer resource YAML file

**Comment by tollercode** [comment]
@Rory-Z 
Logs:
[manager.txt](https://github.com/emqx/emqx-operator/files/12290082/manager.txt)

Manifest:
``` yaml
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx-cluster
  labels: {
    emqx-cluster: emqx-cluster
  }
spec:
  config:
      data: |
        dashboard.listeners.http.bind = 18083
        mqtt {
          peer_cert_as_clientid = "cn"
        }
        listeners.ssl.default {
          bind = "0.0.0.0:8883"
          ssl_options.verify = verify_peer
          ssl_options {
            cacertfile = "/mounted/cert/ca.crt"
            certfile = "/mounted/cert/tls.crt"
            keyfile = "/mounted/cert/tls.key"
          }
        }
  image: "emqx/emqx-enterprise:5.1.1"
  imagePullPolicy: IfNotPresent
  coreTemplate:
    spec:
      volumeClaimTemplates:
        storageClassName: azurefile
        resources:
          requests:
            storage: 20Mi
        accessModes:
        - ReadWriteOnce
      replicas: 2
      toleRations:
        - key: workload
          operator: Equal
          value: mqtt
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - mqtt
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            # Try not to co-locate with nodes from the same cluster
            - weight: 60
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: emqx-cluster
                      operator: In
                      values:
                        - emqx-cluster
                topologyKey: "kubernetes.io/hostname"     
      extraVolumes:
         - name: emqx-tls
           secret:
             secretName: emqx-tls
      extraVolumeMounts:
         - name: emqx-tls
           mountPath: /mounted/cert
  replicantTemplate:
    spec:
      replicas: 0
      extraVolumes:
         - name: emqx-tls
           secret:
             secretName: emqx-tls
      extraVolumeMounts:
         - name: emqx-tls
           mountPath: /mounted/cert
  dashboardServiceTemplate:
    metadata:
      name: emqx-dashboard
    spec:
      type: ClusterIP
      selector:
        apps.emqx.io/db-role: core
      ports:
        - name: "dashboard-listeners-http-bind"
          protocol: TCP
          port: 18083
          targetPort: 18083
  listenersServiceTemplate:
    metadata:
      name: emqx-tls-listener
    spec:
      type: LoadBalancer
      ports:
        - name: "ssl-default"
          protocol: TCP
          port: 8883
          targetPort: 8883
```
