### ISSUE TITLE
EMQX service name can't be customized

### ISSUE THREAD

**Issue by smariko** [emqx/emqx-operator#967]
**Describe the bug**
Impossible to change emqx service name. Operator create a service named "emqx-listeners" by default.
This name stay unchanged after changing the definition file in the metadata.name.

**To Reproduce**
Create a cluster using the definition below:

```
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
spec:
  image: emqx:5.1
  imagePullPolicy: IfNotPresent
  coreTemplate:
    spec:
      volumeClaimTemplates:
        storageClassName: "local-path"
        resources:
          requests:
            storage: 20Mi
        accessModes:
          - ReadWriteOnce
      replicas: 3
  listenersServiceTemplate:
    metadata:
      **name: emqx**
      labels:
        apps.emqx.io/instance: emqx
        apps.emqx.io/managed-by: emqx-operator
    spec:
      selector:
        apps.emqx.io/db-role: core
```
**Expected behavior**
An EMQX cluster with a service named "emqx" instead of "emqx-listerners".

**Anything else we need to know?**:

**Environment details:**: dev
- Kubernetes version: 1.25.6
- Cloud-provider/provisioner: OVH
- emqx-operator version: 2.2.3
- Install method: helm
