### ISSUE TITLE
Error creating /opt/emqx/data/configs: permission denied

### ISSUE THREAD

**Issue by ChPfisterer** [emqx/emqx-operator#97]
Hey guys,

I am trying to run your operator on a local Kubernetes cluster, but get an error in the pod's log:
`kubectl logs emqx-0`         
`2022-01-21T22:58:52.565992+00:00 [error] Error creating /opt/emqx/data/configs: permission denied`

Do you have any idea how I could fix this?
BR, Christian

**Comment by Rory-Z** [comment]
Hi, @ChPfisterer 
Can you share your deployment files?

**Comment by ChPfisterer** [comment]
Hi guys and thank you for coming back to me.

My local K8s deployment consists of 2 VMs in Parallels Desktop on macOS: 1 control plane and one worker node;K8s version 1.21

I also created 6 Persistent Volumes like this:
```apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-emqx-vol1
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/vol1"```

**Comment by kiragoo** [comment]
It seems you set up the  `PV` in `hostPath` mode. Can u share the `CR` yaml about the crd ? @ChPfisterer

**Comment by ChPfisterer** [comment]
In addition:
I did the steps as described in the "getting started" section
1. depoloyed cert-manager
2. deployed operator with Helm with the flag installCRDs=true and --create-namespace

**Comment by Rory-Z** [comment]
> In addition: I did the steps as described in the "getting started" section
> 
> 1. depoloyed cert-manager
> 2. deployed operator with Helm with the flag installCRDs=true and --create-namespace

Hi, @ChPfisterer 
This step just ensures that the emqx operator controller is deployed successfully, I need to know how you are deploying the emqx broker

**Comment by ChPfisterer** [comment]
I guess pretty much the standard way, as described in the getting started:
emqx.yaml
```
## full example
apiVersion: apps.emqx.io/v1beta2
kind: EmqxBroker
metadata:
  name: emqx
spec:
  image: emqx/emqx:4.3.11
  replicas: 3
  labels:
    cluster: emqx
  storage:
    storageClassName: standard
    resources:
      requests:
        storage: 20Mi
    accessModes:
    - ReadWriteOnce
  env:
    - name: "EMQX_LOG__LEVEL"
      value: "debug"
  emqxTemplate:
    listener:
      type: ClusterIP
      ports:
        mqtt: 1883
        mqtts: 8883
        ws: 8083
        wss: 8084
        dashboard: 18083
        api: 8081
    acl:
      - permission: allow
        username: "dashboard"
        action: subscribe
        topics:
          filter:
            - "$SYS/#"
            - "#"
      - permission: allow
        ipaddress: "127.0.0.1"
        topics:
          filter:
            - "$SYS/#"
          equal:
            - "#"
      - permission: deny
        action: subscribe
        topics:
          filter:
            - "$SYS/#"
          equal:
            - "#"
      - permission: allow
    plugins:
      - name: emqx_management
        enable: true
      - name: emqx_recon
        enable: true
      - name: emqx_retainer
        enable: true
      - name: emqx_dashboard
        enable: true
      - name: emqx_telemetry
        enable: true
      - name: emqx_rule_engine
        enable: true
      - name: emqx_bridge_mqtt
        enable: false
    modules:
      - name: emqx_mod_acl_internal
        enable: true
      - name: emqx_mod_presence
        enable: true
```

**Comment by Rory-Z** [comment]
Can you run `kubectl get sc` to check the storageClasses in the cluster?

**Comment by ChPfisterer** [comment]
Oh... :(
```
% kubectl get sc -A
No resources found
```

But
````
% kubectl get pv,pvc 
NAME                            CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                      STORAGECLASS   REASON   AGE
persistentvolume/pv-emqx-vol1   20Mi       RWO            Retain           Bound    default/emqx-data-emqx-0   standard                5m7s
persistentvolume/pv-emqx-vol2   20Mi       RWO            Retain           Bound    default/emqx-log-emqx-2    standard                5m3s
persistentvolume/pv-emqx-vol3   20Mi       RWO            Retain           Bound    default/emqx-log-emqx-0    standard                4m59s
persistentvolume/pv-emqx-vol4   20Mi       RWO            Retain           Bound    default/emqx-data-emqx-1   standard                4m56s
persistentvolume/pv-emqx-vol5   20Mi       RWO            Retain           Bound    default/emqx-log-emqx-1    standard                4m52s
persistentvolume/pv-emqx-vol6   20Mi       RWO            Retain           Bound    default/emqx-data-emqx-2   standard                4m49s

NAME                                     STATUS   VOLUME         CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/emqx-data-emqx-0   Bound    pv-emqx-vol1   20Mi       RWO            standard       11m
persistentvolumeclaim/emqx-data-emqx-1   Bound    pv-emqx-vol4   20Mi       RWO            standard       11m
persistentvolumeclaim/emqx-data-emqx-2   Bound    pv-emqx-vol6   20Mi       RWO            standard       11m
persistentvolumeclaim/emqx-log-emqx-0    Bound    pv-emqx-vol3   20Mi       RWO            standard       11m
persistentvolumeclaim/emqx-log-emqx-1    Bound    pv-emqx-vol5   20Mi       RWO            standard       11m
persistentvolumeclaim/emqx-log-emqx-2    Bound    pv-emqx-vol2   20Mi       RWO            standard       11m
```

**Comment by Rory-Z** [comment]
Sorry, we don't support persistentVolume at the moment, maybe you can try creating a storageClasses

If you're just validating the demo, you can use a minimal profile deployment, which won't turn on storage, like this
```
apiVersion: apps.emqx.io/v1beta2
kind: EmqxBroker
metadata:
  name: emqx
spec:
  image: emqx/emqx:4.3.11
```

**Comment by ChPfisterer** [comment]
Ok. Thank you for investigating.

**Comment by burhanshaikh** [comment]
Hi!
I am getting the same error when I create PVCs - AWS EBS
Creation of PVs via storage class(PVC) do not work, the support for PVs need to be added. Do we have any timeframe/estimates on when this will be shipped?

**Comment by kiragoo** [comment]
@burhanshaikh Can you show  more details about the storage class used, thanks for your feedback.

**Comment by burhanshaikh** [comment]
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
```

```
apiVersion: apps.emqx.io/v1beta2
kind: EmqxBroker
metadata:
  name: emqx
spec:
  image: emqx/emqx:4.4.0
  storage:
    storageClassName: fast-ssd
    resources:
      requests:
        storage: 256Mi
    accessModes:
      - ReadWriteOnce
```
