### ISSUE TITLE
EMQX Heapsize seems 6MB even though it is set to 32MB as default

### ISSUE THREAD

**Issue by memoliyasti** [emqx/emqx-operator#971]
**Describe the bug**
Heapsize seems it is set **6 MB** although it is set to **32 MB** as default.
In /opt/emqx/etc/emqx.conf directory, it seems 32 MB but when we checked the logs from Loki, error that has been occurred show it is related with the **Maximum heapsize reached. Max Heapsize 6291456**. 

**Expected behavior**
We expect to see the values that we set on the chart

**Anything else we need to know?**:
Since we haven't set any heapsize configuration, we expect to have 32 MB heapsize that we can use. Logs that we observed from Loki based on the error, it shows it is reached to max heapsize (6 MB). When I checked the emqx.conf, it shows that it is set 32 MB.

I would like to know why configuration that we have and logs that EMQX created are different. Is there any other missing configuration that we need be aware of?

I am sharing the configuration details below.

```yaml
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  image: {{ .Values.repository }}:{{ .Values.tag }}
  imagePullSecrets:
    - name: {{ .Values.imagePullSecrets }}
  config:
    data: |
      authorization {
        no_match = "deny"
        deny_action = "disconnect"
        sources = [{type: "file", enable: true, path: "/etc/emqx/acl.conf"}]
      }
      dashboard {
        listeners.http {
            bind: 18083
        }
        default_username: "admin"
        default_password: "public"
      }

      force_shutdown {
        enable = "true"
        max_heap_size = "64MB"
        max_mailbox_size = "2000"
      }
      mqtt {
        max_inflight = "10000"
        max_mqueue_len = "7200000"
        max_packet_size = "25MB"
      }
  coreTemplate:
    metadata:
      name: emqx-core
      labels:
        apps.emqx.io/instance: emqx
        apps.emqx.io/db-role: core
        app.kubernetes.io/instance: emqx-core
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - emqx-core
              topologyKey: kubernetes.io/hostname
      replicas: 3
      volumeClaimTemplates:
        storageClassName: {{ .Values.storageClassName }}
        resources:
          requests:
            storage: 4Gi
        accessModes:
          - ReadWriteOnce
      extraVolumes:
        - name: acl
          configMap:
            name: emqx-acl
      extraVolumeMounts:
        - name: acl
          mountPath: "/etc/emqx/acl.conf"
          subPath: acl.conf
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
      podSecurityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: Always
      containerSecurityContext:
        runAsUser: 0
        runAsGroup: 0
      livenessProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 60
        periodSeconds: 30
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 12
  replicantTemplate:
    metadata:
      name: emqx-replicant
      labels:
        apps.emqx.io/instance: emqx
        apps.emqx.io/db-role: replicant
        app.kubernetes.io/instance: emqx-replicant
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - emqx-replicant
              topologyKey: kubernetes.io/hostname
      ports:
        - name: "tcp-replicant"
          protocol: TCP
          containerPort: 18083
      replicas: 3
      command:
        - "/usr/bin/docker-entrypoint.sh"
      args:
        - "/opt/emqx/bin/emqx"
        - "foreground"
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
      extraVolumes:
        - name: acl
          configMap:
            name: emqx-acl
      extraVolumeMounts:
        - name: acl
          mountPath: "/etc/emqx"
      podSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always
        supplementalGroups:
          - 1000
      containerSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      livenessProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 60
        periodSeconds: 30
      readinessProbe:
        httpGet:
          path: /status
          port: 18083
        initialDelaySeconds: 10
        periodSeconds: 5
  listenersServiceTemplate:
    metadata:
      name: emqx-listeners
    spec:
      ports:
        - name: "tcp-api"
          protocol: TCP
          port: 8083
          targetPort: 8083
        - name: "tcp-default"
          protocol: TCP
          port: 1883
          targetPort: 1883
        - name: "tcp-ssl"
          protocol: TCP
          port: 8883
          targetPort: 8883
        - name: "tcp-internal"
          protocol: TCP
          port: 1884
          targetPort: 1884
        - name: "tcp-quic"
          protocol: TCP
          port: 1885
          targetPort: 1885
        - name: "tcp-external"
          protocol: TCP
          port: 1886
          targetPort: 1886
  dashboardServiceTemplate:
    metadata:
      name: emqx-dashboard
    spec:
      ports:
        - name: "tcp-http"
          protocol: TCP
          port: 18083
          targetPort: 18083
  updateStrategy:
    evacuationStrategy:
      connEvictRate: 1000
      sessEvictRate: 1000
      waitTakeover: 10
    initialDelaySeconds: 10
    type: Recreate
```

And also, after specifying the heapsize value to 32 on the chart, it shows different logs now. I am sharing the two logs before/after updating configuration. It seems it is not set to 32 MB after setting the heapsize configuration

Logs before configuring heapsize

<img width="1083" alt="image" src="https://github.com/emqx/emqx-operator/assets/79761080/836532c2-667b-46b6-9d91-8b4533da1d56">

Logs after configuring heapsize

<img width="1695" alt="image" src="https://github.com/emqx/emqx-operator/assets/79761080/643ded2c-fb29-4dcd-83cd-c0496563e087">

This is the configuration I see on the **/opt/emqx/etc/emqx.conf**

![image](https://github.com/emqx/emqx-operator/assets/79761080/c00194eb-6312-4ec0-af98-0070e9e030f7)

**Environment details:**:
- Kubernetes version: v1.24.9
- Cloud-provider/provisioner: OnPrem
- emqx-operator version: emqx-operator-2.2.2
- Install method: helm
